# Generated by Django 4.1.3 on 2022-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_equipment_cleaner_cleaner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_brand',
            field=models.CharField(max_length=120),
        ),
    ]
